"""Unified workspace directory for Definable runtime artifacts.

Two-tier architecture:
  - ``~/.definable/`` — global (user home): model cache, bridge tokens, CLI history
  - ``.definable/`` — project-local (cwd-relative): memory, traces, identity, tool cache

Resolution order for project-local paths:
  1. Explicit param passed to component (e.g. ``SQLiteStore(db_path="/my/db")``)
  2. ``DEFINABLE_ROOT`` environment variable (sets the project root)
  3. Current working directory (default)

The ``.definable/`` directory is created lazily — only when a component first
writes to it. Import alone creates nothing.

Example::

    from definable.utils.workspace import workspace_path

    # Resolves to ./.definable/memory.db (or $DEFINABLE_ROOT/.definable/memory.db)
    db_path = workspace_path("memory.db")

    # Resolves to ./.definable/traces/ (creates parent dirs)
    trace_dir = workspace_path("traces")

    # Get the workspace root without creating anything
    from definable.utils.workspace import get_workspace_dir
    ws = get_workspace_dir()  # Path(".definable")
"""

import os
from pathlib import Path

_DIR_NAME = ".definable"

_GITIGNORE_CONTENT = """\
# Auto-generated by Definable — runtime artifacts, not source code.
# Remove specific lines below if you want to commit certain artifacts.
*
!.gitignore
"""


def get_project_root() -> Path:
  """Return the project root directory.

  Uses ``DEFINABLE_ROOT`` env var if set, otherwise the current working directory.
  """
  return Path(os.environ.get("DEFINABLE_ROOT", ".")).resolve()


def get_workspace_dir() -> Path:
  """Return the project-local workspace directory path.

  Does NOT create the directory — call ``ensure_workspace()`` or use
  ``workspace_path()`` for that.
  """
  return get_project_root() / _DIR_NAME


def ensure_workspace() -> Path:
  """Create the workspace directory and seed ``.gitignore`` if it doesn't exist.

  Returns the workspace directory path.
  """
  ws = get_workspace_dir()
  if not ws.exists():
    ws.mkdir(parents=True, exist_ok=True)
    gitignore = ws / ".gitignore"
    if not gitignore.exists():
      gitignore.write_text(_GITIGNORE_CONTENT, encoding="utf-8")
  return ws


def workspace_path(*segments: str, mkdir: bool = True) -> Path:
  """Resolve a path within the workspace directory.

  Args:
    *segments: Path segments relative to the workspace root.
        e.g. ``workspace_path("memory.db")`` or ``workspace_path("traces")``.
    mkdir: If True (default), create parent directories.

  Returns:
    Absolute ``Path`` within the ``.definable/`` workspace.
  """
  ws = ensure_workspace()
  path = ws.joinpath(*segments)
  if mkdir:
    # For files (have suffix), create parents. For dirs, create the dir itself.
    if path.suffix:
      path.parent.mkdir(parents=True, exist_ok=True)
    else:
      path.mkdir(parents=True, exist_ok=True)
  return path
